"""empty message

Revision ID: 32996a5a74dc
Revises: 631cd67af514
Create Date: 2017-04-08 10:51:55.202078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32996a5a74dc'
down_revision = '631cd67af514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('img', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'img')
    # ### end Alembic commands ###
