"""empty message

Revision ID: bc81e9ba0377
Revises: 32996a5a74dc
Create Date: 2017-04-08 11:02:57.966222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc81e9ba0377'
down_revision = '32996a5a74dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('summary', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'summary')
    # ### end Alembic commands ###
