"""empty message

Revision ID: 631cd67af514
Revises: 83c2e7e8212b
Create Date: 2017-04-07 12:29:31.896110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631cd67af514'
down_revision = '83c2e7e8212b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=254), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mailing')
    # ### end Alembic commands ###
